### ISSUE TITLE
ip2long问题

### ISSUE THREAD

**Issue by xianyunyh** [hookover/php-engineer-interview-questions#2]
官方文档 [http://php.net/manual/zh/function.ip2long.php](http://php.net/manual/zh/function.ip2long.php)
> 因为PHP的 integer 类型是有符号，并且有许多的IP地址讲导致在32位系统的情况下为负数， 你需要使用 "%u" 进行转换通过 sprintf() 或 printf() 得到的字符串来表示无符号的IP地址。

**Comment by walijoy** [comment]
太棒了，希望你能提交修改代码，哈哈

**Comment by walijoy** [comment]
已处理
