### ISSUE TITLE
http与https的主要区别?

### ISSUE THREAD

**Issue by xianyunyh** [hookover/php-engineer-interview-questions#7]
关于http与https的主要区别。
文中的说法有点问题。
http在应用层。这是对的。
但https 并不在传输层。
https 只是在传输层和应用层之间加入TLS层。进行数据加密。 
传输层协议。目前常见的有TCP/UDP
![image](https://user-images.githubusercontent.com/7820848/40315490-1b7d26f6-5d4e-11e8-90a2-4961aec8969f.png)

**Comment by walijoy** [comment]
ssl在传输层之上应用层之间（表示层绘画层？）进行工作，那如何表示http和https之间的区别呢？

这样说是否准确呢？
HTTPS是在传输层与应用层之间使用SSL/TLS加密的HTTP
与HTTP类似，HTTPS本身是应用层的协议

**Comment by xianyunyh** [comment]
上图是OSI七层的模型图。所以有表示层、会话层。
在TCP/IP协议模型中。上面三层都划为应用层。
HTTPS和HTTPS的区别和联系见下图
![image](https://user-images.githubusercontent.com/7820848/40339055-16964250-5dab-11e8-8d0a-b3dff6402ac3.png)

**Comment by walijoy** [comment]
我在这里看的是SSL是属于OSI模型中的传输层，
https是建立在ssl信道上的的http，所以我觉得它也是基于传输层的
https://zh.wikipedia.org/wiki/OSI%E6%A8%A1%E5%9E%8B


但如果是从TCP/IP四层模型来讲，则ssl处于应用层
https://zh.wikipedia.org/wiki/TCP/IP%E5%8D%8F%E8%AE%AE%E6%97%8F

**Comment by xianyunyh** [comment]
OSI模型 把应用层细化了。HTTP和HTTPS都是基于TCP协议。利用TCP进行传输数据。传输层之上的协议都可以成为应用层协议。
